<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://itq.edu/soa/hw" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://itq.edu/soa/hw" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://itq.edu/soa/hw">
			<xs:include schemaLocation="HelloWorld.xsd"/>
		</xs:schema>
  </wsdl:types>
  <wsdl:message name="saludarMessageResponse">
    <wsdl:part name="parameter" element="tns:response">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="saludarMessageRequest">
    <wsdl:part name="parameter" element="tns:request">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="saludarPortType">
    <wsdl:operation name="saludarOperation">
      <wsdl:input message="tns:saludarMessageRequest">
    </wsdl:input>
      <wsdl:output message="tns:saludarMessageResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="saludarBinding" type="tns:saludarPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="saludarOperation">
      <soap:operation soapAction="http://itq.edu/soa/hw/saludarOperacion"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="saludarService">
    <wsdl:port name="saludarPort" binding="tns:saludarBinding">
      <soap:address location="http://localhost:8080/axis2/services/saludarService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
