<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soa.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://soa.com" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://soa.com">
			<xs:include schemaLocation="buro.xsd"/>
		</xs:schema>
  </wsdl:types>
  <wsdl:message name="buroMessageResponse">
    <wsdl:part name="parameter" element="tns:consultarBuroResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="buroMessageRequest">
    <wsdl:part name="parameter" element="tns:consultarBuroRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="buroPortType">
    <wsdl:operation name="buroOperation">
      <wsdl:input message="tns:buroMessageRequest">
    </wsdl:input>
      <wsdl:output message="tns:buroMessageResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="buroBinding" type="tns:buroPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="buroOperation">
      <soap:operation soapAction="http://soa.com/consultarBuro"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="buroService">
    <wsdl:port name="buroPort" binding="tns:buroBinding">
      <soap:address location="No Target Adress"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
