<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://soa.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://soa.com" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wsdl:types>
    <xs:schema elementFormDefault="qualified" targetNamespace="http://soa.com">
			<xs:include schemaLocation="credito.xsd"/>
		</xs:schema>
  </wsdl:types>
  <wsdl:message name="generarTablaMessageResponse">
    <wsdl:part name="parameter" element="tns:tablaAmortizacionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="generarTablaMessageRequest">
    <wsdl:part name="parameter" element="tns:tablaAmortizacionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="generarTablaPortType">
    <wsdl:operation name="generarTablaOperation">
      <wsdl:input message="tns:generarTablaMessageRequest">
    </wsdl:input>
      <wsdl:output message="tns:generarTablaMessageResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="generarTablaBinding" type="tns:generarTablaPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="generarTablaOperation">
      <soap:operation soapAction="http://soa.com/generarTablaOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="generarTablaService">
    <wsdl:port name="generarTablaPort" binding="tns:generarTablaBinding">
      <soap:address location="No Target Adress"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
